// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_path_ from "./routes/api/[...path].ts";
import * as $index from "./routes/index.tsx";
import * as $map from "./routes/map.tsx";
import * as $streams_id_ from "./routes/streams/[id].tsx";
import * as $streams_index from "./routes/streams/index.tsx";
import * as $StationMap from "./islands/StationMap.tsx";
import * as $StreamConditionsCard from "./islands/StreamConditionsCard.tsx";
import * as $StreamList from "./islands/StreamList.tsx";
import * as $TopPicks from "./islands/TopPicks.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/[...path].ts": $api_path_,
    "./routes/index.tsx": $index,
    "./routes/map.tsx": $map,
    "./routes/streams/[id].tsx": $streams_id_,
    "./routes/streams/index.tsx": $streams_index,
  },
  islands: {
    "./islands/StationMap.tsx": $StationMap,
    "./islands/StreamConditionsCard.tsx": $StreamConditionsCard,
    "./islands/StreamList.tsx": $StreamList,
    "./islands/TopPicks.tsx": $TopPicks,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
