// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from './routes/_app.tsx';
import * as $_middleware from './routes/_middleware.ts';
import * as $api_middleware from './routes/api/_middleware.ts';
import * as $api_hatches_id_ from './routes/api/hatches/[id].ts';
import * as $api_hatches_index from './routes/api/hatches/index.ts';
import * as $api_predict from './routes/api/predict.ts';
import * as $api_shops_index from './routes/api/shops/index.ts';
import * as $api_stations_id_history from './routes/api/stations/[id]/history.ts';
import * as $api_stations_id_index from './routes/api/stations/[id]/index.ts';
import * as $api_stations_id_stats from './routes/api/stations/[id]/stats.ts';
import * as $api_streams_id_conditions from './routes/api/streams/[id]/conditions.ts';
import * as $api_streams_id_index from './routes/api/streams/[id]/index.ts';
import * as $api_streams_index from './routes/api/streams/index.ts';
import * as $api_top_picks from './routes/api/top-picks.ts';
import * as $hatches_index from './routes/hatches/index.tsx';
import * as $index from './routes/index.tsx';
import * as $map from './routes/map.tsx';
import * as $shops_id_ from './routes/shops/[id].tsx';
import * as $shops_index from './routes/shops/index.tsx';
import * as $streams_id_ from './routes/streams/[id].tsx';
import * as $streams_index from './routes/streams/index.tsx';
import * as $HatchChart from './islands/HatchChart.tsx';
import * as $HistoryChart from './islands/HistoryChart.tsx';
import * as $StationMap from './islands/StationMap.tsx';
import * as $StreamConditionsCard from './islands/StreamConditionsCard.tsx';
import * as $StreamList from './islands/StreamList.tsx';
import * as $TopPicks from './islands/TopPicks.tsx';
import type { Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/_app.tsx': $_app,
    './routes/_middleware.ts': $_middleware,
    './routes/api/_middleware.ts': $api_middleware,
    './routes/api/hatches/[id].ts': $api_hatches_id_,
    './routes/api/hatches/index.ts': $api_hatches_index,
    './routes/api/predict.ts': $api_predict,
    './routes/api/shops/index.ts': $api_shops_index,
    './routes/api/stations/[id]/history.ts': $api_stations_id_history,
    './routes/api/stations/[id]/index.ts': $api_stations_id_index,
    './routes/api/stations/[id]/stats.ts': $api_stations_id_stats,
    './routes/api/streams/[id]/conditions.ts': $api_streams_id_conditions,
    './routes/api/streams/[id]/index.ts': $api_streams_id_index,
    './routes/api/streams/index.ts': $api_streams_index,
    './routes/api/top-picks.ts': $api_top_picks,
    './routes/hatches/index.tsx': $hatches_index,
    './routes/index.tsx': $index,
    './routes/map.tsx': $map,
    './routes/shops/[id].tsx': $shops_id_,
    './routes/shops/index.tsx': $shops_index,
    './routes/streams/[id].tsx': $streams_id_,
    './routes/streams/index.tsx': $streams_index,
  },
  islands: {
    './islands/HatchChart.tsx': $HatchChart,
    './islands/HistoryChart.tsx': $HistoryChart,
    './islands/StationMap.tsx': $StationMap,
    './islands/StreamConditionsCard.tsx': $StreamConditionsCard,
    './islands/StreamList.tsx': $StreamList,
    './islands/TopPicks.tsx': $TopPicks,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
