name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --depth 1 http://100.78.158.46:3000/ward/upstate-fishing.git .
      - run: deno --version
      - run: deno fmt --check
      - run: deno lint
      - run: deno check src/**/*.ts
      - run: deno test --allow-net --allow-env --allow-read
