name: CI

on:
  push:
    branches: [main, epic/*, feature/*]
  pull_request:
    branches: [main, epic/*]

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git" repo
          cd repo
          git fetch origin "${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"
          git checkout "${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}" 2>/dev/null || git checkout "$GITHUB_SHA" || true

      - name: Deno version
        run: deno --version

      - name: Format check
        run: cd repo && deno fmt --check

      - name: Lint
        run: cd repo && deno lint

      - name: Type check
        run: cd repo && deno check src/**/*.ts

      - name: Tests
        run: cd repo && deno test --allow-net --allow-env --allow-read
