name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone --depth 1 http://100.78.158.46:3000/ward/upstate-fishing.git repo
          cd repo
          deno --version
          deno fmt --check
          deno lint
