name: CI

on:
  push:
    branches: [main, epic/*, feature/*]
  pull_request:
    branches: [main, epic/*]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Test runner
        run: |
          echo "Hello from CI runner!"
          hostname
          whoami
          deno --version
