name: CI

on:
  push:
    branches: [main, epic/*, feature/*]
  pull_request:
    branches: [main, epic/*]

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone http://100.78.158.46:3000/ward/upstate-fishing.git repo
          cd repo
          git fetch origin $GITHUB_SHA --depth=1 || git fetch origin $GITHUB_REF --depth=1 || true
          git checkout $GITHUB_SHA || git checkout $GITHUB_HEAD_REF || git checkout main

      - name: Deno version
        run: deno --version

      - name: Format check
        run: cd repo && deno fmt --check

      - name: Lint
        run: cd repo && deno lint

      - name: Type check
        run: cd repo && deno check src/**/*.ts

      - name: Tests
        run: cd repo && deno test --allow-net --allow-env --allow-read
