name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        run: git clone --depth 1 http://100.78.158.46:3000/ward/upstate-fishing.git
      - name: List files
        run: ls -la upstate-fishing/
