name: CI

on:
  push:
    branches: [main, epic/*, feature/*]
  pull_request:
    branches: [main, epic/*]

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deno version
        run: deno --version

      - name: Format check
        run: deno task fmt --check

      - name: Lint
        run: deno task lint

      - name: Type check
        run: deno task check

      - name: Tests
        run: deno task test
