name: CI

on:
  push:
    branches: [main, epic/*, feature/*]
  pull_request:
    branches: [main, epic/*]

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout (manual)
        run: |
          git clone --depth 1 --branch ${{ github.head_ref || github.ref_name }} \
            http://localhost:3000/${{ github.repository }}.git .
          git checkout ${{ github.sha }}

      - name: Check Deno version
        run: deno --version

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Type check
        run: deno check src/**/*.ts

      - name: Run tests
        run: deno test --allow-net --allow-env --allow-read
