name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --depth 1 http://100.78.158.46:3000/ward/upstate-fishing.git repo
      - run: cd repo && deno --version
      - run: cd repo && deno fmt --check
      - run: cd repo && deno lint
